spring.application.name=smartcart

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/smartcart}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect